apiVersion: v1
kind: Service
metadata:
  name: artifactory-rproxy
  namespace: REPLACE_WITH_NAMESPACE
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080-tcp
  selector:
    name: artifactory-rproxy
