apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-rproxy
data:
  supervisord.conf: |
    [supervisord]
    logfile=/tmp/supervisord.log
    pidfile=/tmp/supervisord.pid
    nodaemon=true

    [program:fontawesome-https]
    command=socat -d TCP4-LISTEN:9443,bind=127.0.0.1,reuseaddr,fork PROXY:REPLACE_WITH_CORPORATE_PROXY:npm.fontawesome.com:443
    priority=0

    [program:fontawesome-http]
    command=socat -d TCP4-LISTEN:9080,bind=127.0.0.1,reuseaddr,fork OPENSSL:127.0.0.1:9443,commonname=npm.fontawesome.com
    priority=1

    [program:nginx]
    command=sh -c $STI_SCRIPTS_PATH/run
    priority=2
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>artifactory-rproxy</title>
    </head>
    <body>
        <h1>artifactory-rproxy</h1>
        <p>Hello, Proxy!</p>
    </body>
    </html>
  nginx.conf: |
    error_log  /dev/stderr  warn;
    pid  /tmp/nginx.pid;
    worker_processes  auto;
    worker_cpu_affinity  auto;

    events {
        worker_connections  1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /dev/stdout  main;

        include  /etc/opt/rh/rh-nginx114/nginx/mime.types;
        default_type  application/octet-stream;

        server {
            listen  8080;
            server_name  _;
            root  /opt/rh/rh-nginx114/root/usr/share/nginx/html;

            location = / {
            }

            location / {
                return  404;
            }

            location = /index.html {
            }

            location = /fontawesome {
                return  302  $http_x_forwarded_proto://$host/fontawesome/;
            }

            location /fontawesome/ {
                proxy_http_version  1.1;
                proxy_pass  http://127.0.0.1:9080/;
                proxy_redirect  https://npm.fontawesome.com/  $http_x_forwarded_proto://$host/fontawesome/;

                proxy_set_header  Accept-Encoding  '';
                proxy_set_header  Connection  '';
                proxy_set_header  Forwarded  '';
                proxy_set_header  X-Forwarded-For  '';
                proxy_set_header  X-Forwarded-Host  '';
                proxy_set_header  X-Forwarded-Port  '';
                proxy_set_header  X-Forwarded-Proto  '';

                proxy_set_header  Host  npm.fontawesome.com;
                proxy_set_header  Authorization  'Bearer REPLACE_WITH_FONTAWESOME_TOKEN';

                sub_filter_types  application/vnd.npm.install-v1+json  application/json;
                sub_filter  '"tarball":"https://npm.fontawesome.com/'  '"tarball":"$http_x_forwarded_proto://$host/fontawesome/';
                sub_filter_once  off;
            }
        }
    }
