apiVersion: v1
kind: Route
metadata:
  name: artifactory-rproxy
  annotations:
    haproxy.router.openshift.io/timeout: 300s
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: "true"
spec:
  host: REPLACE_WITH_HOSTNAME
  port:
    targetPort: http-alt
  to:
    kind: Service
    name: artifactory-rproxy
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
