apiVersion: v1
kind: BuildConfig
metadata:
  name: nginx-114-socat-rhel7
  namespace: REPLACE_WITH_NAMESPACE
spec:
  completionDeadlineSeconds: 300
  source:
    type: Dockerfile
    dockerfile: |
      FROM nginx-114-rhel7:latest
      USER 0
      RUN export http_proxy=REPLACE_WITH_HTTP_PROXY && \
          export https_proxy=REPLACE_WITH_HTTPS_PROXY && \
          export no_proxy=REPLACE_WITH_NO_PROXY && \
          rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release && \
          yum -y --enablerepo=rhel-server-rhscl-7-rpms --setopt=tsflags=nodocs install \
              python27 \
              python27-python-devel \
              python27-python-pip \
              python27-python-setuptools \
              socat && \
          yum clean all && \
          rm -rf /var/cache/yum && \
          echo "source scl_source enable python27" 1>>/opt/app-root/etc/scl_enable && \
          $PROMPT_COMMAND && \
          pip install -i REPLACE_WITH_PYTHON_REPOSITORY --no-cache-dir \
              supervisor
      USER 1001
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: nginx-114-rhel7:latest
        forcePull: true
  output:
    to:
      kind: ImageStreamTag
      name: nginx-114-socat-rhel7:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
